[package]
name = "faster_xml_nif"
version = "0.1.5"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]
edition = "2021"

[lib]
name = "faster_xml_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34"
quick-xml = "0.36"
chrono = "0.4"
