[package]
name = "faster_xml_nif"
version = "0.1.4"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]
edition = "2018"

[lib]
name = "faster_xml_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
quick-xml = "0.26"
chrono = "0.4"
