name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Erlang
      uses: gleam-lang/setup-erlang@v1.1.0
      with:
        otp-version: 22.3
          
    - uses: actions/checkout@v2

    - name: Run build and xref
      run: rebar3 xref

    - name: Run unit tests
      run: rebar3 eunit

    - name: Run Common Test
      run: rebar3 ct
