# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest, windows-latest]

    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Erlang
      # You may pin to the exact commit or the version.
      # uses: gleam-lang/setup-erlang@835e12d085ddd1454946543a4d4892d18aaad5e7
      uses: gleam-lang/setup-erlang@v1.1.0
      with:
        # Version of OTP to install
        otp-version: 22.3
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Run build and xref
      run: escript rebar3 xref

    # Runs a single command using the runners shell
    - name: Run unit tests
      run: escript rebar3 eunit

    # Runs a set of commands using the runners shell
    - name: Run Common Test
      run: escript rebar3 ct
