name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows]
        otp: [22, 23, 24]

    runs-on: ${{ matrix.os }}-latest
    
    steps:
    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
          
    - uses: actions/checkout@v2

    - name: Run build and xref
      run: rebar3 xref

    - name: Run unit tests
      run: rebar3 eunit

    - name: Run Common Test
      run: rebar3 ct
